### ISSUE TITLE
Question regarding Android `core` and `app` structure

### ISSUE THREAD

**Issue by nain-F49FF806** [ianthetechie/uniffi-starter#1]
Hi, thanks, for creating and sharing this template!

There readme [here](https://github.com/ianthetechie/uniffi-starter?tab=readme-ov-file#android) says 
>  Note that the app target is intentionally left blank.

Could you expand on this? 

I assume this is where we would insert the intended actual app UI logic for the app we want to build. 
Am a bit new to android development, so please forgive if this is a basic question:
- Are we supposed to somehow load the 'core' as dependency into the 'app'? If so how? 
  Or is 'core' simply the template which we are to learn from, and redo the loading of the Kotlin file in `app`

**Comment by ianthetechie** [comment]
Hey, thanks for the question @nain-F49FF806!

> I assume this is where we would insert the intended actual app UI logic for the app we want to build.
Am a bit new to android development, so please forgive if this is a basic question:

Yes, exactly. This is where you would add your Android app code. I've created a project but it doesn't have anything in it.

I guess I didn't think it was that interesting since I wasn't attempting to make an Android app tutorial (there are thousands of those), but to show how you would use it in your Kotlin code on Android.

> Are we supposed to somehow load the 'core' as dependency into the 'app'? If so how?
> Or is 'core' simply the template which we are to learn from, and redo the loading of the Kotlin file in app

Yeah, I can explain that a bit. The project uses Gradle, the primary (almost only?) build system for Android apps. It's _ridiculously_ complex and allows for some truly insane structures.

What I've done here is fairly standard, and uses a gradle _workspace_ which contains multiple _projects_. Regrettably even the best tools (Android Studio and IntelliJ notably) still don't make it easy to set up your project in this manner, despite it being industry standard. That was actually part of my motivation for creating this repo.

Background aside, how does it work? If you take a look at [settings.gradle](https://github.com/ianthetechie/uniffi-starter/blob/bb0bc1e1a7ac04df1188774b461e32da2818d602/android/settings.gradle#L16), you'll see how the subprojects are set up. There are two projects: `app` and `core`.

The `core` project is a library that talks to your Rust code and provides a higher-level interface to Kotlin. This is _my opinion_ of how most projects will be set up, but my word is definitely not law on this. You can dispense with the core project if all you want do do is call into the Rust code using the generated bindings. I believe it's often beneficial to offer a slightly more opinionated wrapper than auto-generated bindings can provide though, so I've included a `core` project in my starter setup.

The `core` [build.gradle](https://github.com/ianthetechie/uniffi-starter/blob/bb0bc1e1a7ac04df1188774b461e32da2818d602/android/core/build.gradle#L48) automatically does the Rust build and generates bindings. The classes within that project expose the high-level interface, which is what your `app` would access.

As for how to link the core in as a dependency... I forgot that part! oops! Pushing a fix to explain that right now :) I've also thrown in a Jetpack Compose example to show it in action (though it's no different and actually a lot simpler than the unit tests in the core project).

**Comment by nain-F49FF806** [comment]
Hi, thanks! I also independently came to the answer through lots of searching, YouTube and AI assistance. 

I managed to create a functioning app too. Will be uploading it shortly :). Your starter template has been a great starting point. And I believe it would be even more accessible now with your latest additions.  

Thank you! For the starter template, and also for your answer and explanation.

**Comment by ianthetechie** [comment]
This comment made my day ;) Feel free to open further issues if you run into anything else. I'm sure there are other non-obvious things that I missed haha.

**Comment by nain-F49FF806** [comment]
Hi, just an update. [*Share Paste*] is now live on GitHub.   
It's my first Android app! 

It uses a rust library for encrypting text before sharing online
Thanks again for the _uniffi-starter_ kit. 

[*Share Paste*]: https://github.com/nain-F49FF806/sharepaste.oo

**Comment by ianthetechie** [comment]
That's so cool! Thanks for sharing! Really glad I could help get your project off the ground! I'm laughing out loud that my "foobar" placeholder ended up in the final version :D

**Comment by nain-F49FF806** [comment]
Haha, yes, I kept it as a sort of "_control group_". To rule out build / bindings generation issues from the gradle script, before assuming a specific problem in the evolving uniffi code of the library I use.
